spring:
  application:
    name: spring-cloud-eureka-server
server:
  port: 8910
eureka:
#  instance:
#    hostname: peer1
  client:
    #registerWithEureka 和 fetchRegistry 设置为false，表明自己属于服务中心主体
    registerWithEureka: false #是否将自己注册到eureka server，构建集群环境时，需将自己注册到集群中，默认为true
    fetchRegistry: false #是否从eureka server获取注册信息，构建集群环境时，需同步其他eureka server节点，默认为true
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/